### PR TITLE
Add Bottom Navigation

### PR DESCRIPTION
**Pull request by jeffreyAaron**
Added Bottom Navigation bar.
The bottom navigation bar required large changes to the structure to app:
- MainActivity and Aquarium were changed from Activity to Fragments (Note: Fragments don't support onClick attribute. On click will have to be set with OnClickListener)
- OnCreate() was changed to OnCreateView() (because MainActivity and Aquarium are now fragments)
- A new Menu called bottom_nav_menu.xml was created. This is where to go to edit the bottom nav bar.
- A new NavGraph called mobile_navigation.xml was created. This handles navigation within the app and is needed for the bottom navigation bar. (Make sure to set the start position in the NavGraph when making changes or there will a runtime error)

Bottom Navigation Bar Features:
- Icons + Label (Label hides and shows depending on what page you are on)
- Home Page, To Do Page, Aquarium Page, Settings Page
- The new To Do page is where the user can create to do lists that don't fit well with the calendar scheduling or don't need the Pomodoro strategy (ex. Grocery List, Steps to Complete a Project, List of Assignments)
- The Aquarium is now integrated into bottom nav bar making it feel more integrated into the application

**Important Note:** Only the MainActivity, Aquarium, To Do Page, and the Settings page will have the navBar. Once the user leaves the MainActivity by clicking on a day in the calendar, the nav bar will leave because the user is entering a new Activity. I decided that it was not logical to keep the navBar in the DailyTaskView, NewTask, or PerformTask activities because of how the user is supposed to flow through our app. Also adding the navBar to all of the pages that I mentioned would take an even larger restructuring of our app.

Notes:
- Since the Aquarium has been changed to a fragment, please check it. I have tested the Aquarium and it is functional and working.
- Icon need to be changed (We will need the graphic designers to create icons for the navbar)

### CODE REVIEW

**Review by FlyOrBoom — COMMENTED** [review]
The file structure is starting to look messy. How come MainActivity is a fragment now?

**Comment by jeffreyAaron** [comment]
MainActivity must be a fragment for the bottom navigation to work. It only supports fragments. If you want I can clean up the file structure.

**Comment by jeffreyAaron** [comment]
Lets move this chat to Discord.

**Review by FlyOrBoom — APPROVED** [review]
Looks good

**Pull request merged**
